### ISSUE TITLE
OpenStack installieren

### ISSUE THREAD

**Issue by rassulrakhim** [rassulrakhim/NoNameNeeded#10]
* OpenStack auf allen 4 Servern einrichten

**Comment by mxkyb** [comment]
Aus der Mail von Alexander Acker:

> Ihr müsst das zweite Netzwerkinterface der Nodes konfigurieren und aktivieren. Nutzt bitte folgendes IP-Muster: 10.0.42.<Nummer des jeweiligen wally-Nodes>
> z.B.: Für wally142 --> 10.0.42.142
