### ISSUE TITLE
Scrum Refinement

### ISSUE THREAD

**Issue by rassulrakhim** [rassulrakhim/NoNameNeeded#15]
* Welche Konzepte von Scrum passen für uns?
* Wie organisieren wir unsere Treffen? Wie oft? Wann? 
* Können wir unser Issue-Management noch verbessern?

**Comment by liyvde** [comment]
__Offene Fragen für die Gruppe:__

* Wann und wie viele Treffen sollen wir machen?
  * Montag: 18Uhr als Zwischenbesprechung und Gruppenarbeitstermin
  * EVTL. noch zwei __kurze__ Termine zum klären kleinerer Probleme/ zur Coordination?
* Ist es für alle ok, dass wir das über Discord machen?

__Möglicher Wochenplan:__

* Sprintwoche:

Wochentag | Planung
--- | ---
Donnerstag | 14.00 - 16.00 : Stakeholder-Termin<br/>SPRINTBEGINN<br />16.00 - 16.30 : kurze letzte Absprache zur nächsten Woche <br/><ul><li>Klärung von Fragen nach Stakeholder-Termin</li><li>Zuweisung der Tasks</li></ul>
Freitag | Arbeit an Tasks
Samstag | Arbeit an Tasks
Sonntag | Arbeit an Tasks
Montag | Arbeit an Tasks<br/>18.00 - 19.00 (open end) : Weekly<br/><ul><li>Durchsprache des aktuellen Fortschritts</li><li>bei Bedarf Gruppenarbeit</li></ul>
Dienstag | Arbeit an Tasks
Mittwoch | Arbeit an Tasks<br/>20.00 - 20.30 : letzte Rücksprache vor Stakeholder-Termin<br/><ul><li>Klärung vorzustellender Tasks/ Features</li><li>bei Bedarf letzte Gruppenarbeit/ Bug-Fixes</li></ul>
Donnerstag | SPRINTENDE<br/>14.00 - 16.00 : Stakeholder-Termin

* Planungswoche:

Wochentag | Planung
--- | ---
Donnerstag | SPRINTENDE<br/>14.00 - 16.00 : Stakeholder-Termin<br/>16.00 - 16.30 : kurze letzte Absprache zur nächsten Woche<br/><ul><li>Wahl der User-Stories</li><li>falls viel User-Story-Research: Aufteilung Research</li></ul>
Freitag | User-Story-Research
Samstag | User-Story-Research
Sonntag | User-Story-Research
Montag | User-Story-Research<br/>18.00 - 19.00 (open end) : Sprintplanung<br/><ul><li>Rücksprache zu Problemen in letztem Sprint</li><li>Durchsprache der aus Research<br/>entstandenen Tasks aktuell entstandenen Tasks</li><li>bei Bedarf Gruppenarbeit</li></ul>
Dienstag | Task-Refinement
Mittwoch | Task-Refinement<br/>20.00 - 20.30 : letzte Rücksprache vor Stakeholder-Termin<br/><ul><li>Zuweisung der Tasks</li><li>bei Bedarf letzte Gruppenarbeit: Refinement</li></ul>
Donnerstag | 14.00 - 16.00 : Stakeholder-Termin<br/>SPRINTBEGINN
