### ISSUE TITLE
Automate Node SetUp

### ISSUE THREAD

**Issue by liyvde** [rassulrakhim/NoNameNeeded#17]
* Ansible-Playbook oder Shell Script
* Netzwerkinterface einrichten, Docker-Version kontrollieren, Dependencies kontrollieren

**Comment by mxkyb** [comment]
Lasst uns das hier im nächsten Sprint weiter verfolgen, damit wir nicht das Risiko eingehen, die im Moment laufende OpenStack Konfiguration zu zerschießen und unser Dashboard für die Präsentation funktioniert.

**Comment by mxkyb** [comment]
Vorschlag zum weiteren Verfahren: Die weitere Automatisierung der OpenStack installation ist im Prinzip Bugfixing vom Kolla Projekt. Ein profesionelles Vorgehen wäre darum meiner Meinung nach nicht, instabile Workarounds in unsere Scripte einzubauen, sondern unseren Shareholder davon zu überzeugen, dass er Geld für eine zusätzliche Arbeitskraft zur Verfügung stellen muss, die für das Kolla-Projekt die Bugs im Setup behebt, die bei uns auftreten.
