### ISSUE TITLE
FirstLogin

### ISSUE THREAD

**Issue by rassulrakhim** [rassulrakhim/NoNameNeeded#19]
Nachdem erfolgreichem Installation von OpenStack müssen wir uns auf Horizon anmelden können.
Dashboard befindet sich unter IP-Adresse von Controll-Node mit /dashboard.
Die Credentials befinden sich unter /root/keystonerc_ im File keystonerc_admin.

**Comment by liyvde** [comment]
Issues hinzugefügt zu https://github.com/rassulrakhim/NoNameNeeded/issues/16
