### ISSUE TITLE
Erstelle User mit Role Member

### ISSUE THREAD

**Issue by rassulrakhim** [rassulrakhim/NoNameNeeded#22]
__Schritte:__
1. Login als Admin (siehe Ticket FirstLogin)
2. Links Users im Tab Identity auswählen. 
3. Drücke "Create User".
4. Füge DomainName, Username und Passwort für User ein. Email muss rein als auch die Projekte, zu dennen User gehört( siehe Ticket https://github.com/rassulrakhim/NoNameNeeded/issues/21). Domain ID sollte Default bleiben.
5. "Create User" drücken.

Bitte mit Login testen.
Hilfreich: https://docs.openstack.org/horizon/latest/admin/manage-projects-and-users.html

**Comment by mxkyb** [comment]
user erstellt, aber braucht noch ein projekt um sich einloggen zu können.
